-- MySQL Script generated by MySQL Workbench
-- qua 13 jan 2021 20:32:54 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema knowledgeBase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema knowledgeBase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `knowledgeBase` ;
USE `knowledgeBase` ;

-- -----------------------------------------------------
-- Table `knowledgeBase`.`sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgeBase`.`sections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `subtitle` VARCHAR(250) NOT NULL,
  `slug` VARCHAR(100) NOT NULL,
  `created_by` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(100) NOT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `knowledgeBase`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgeBase`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `slug` VARCHAR(100) NOT NULL,
  `created_by` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(100) NOT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `knowledgeBase`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgeBase`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `subtitle` VARCHAR(250) NOT NULL,
  `slug` VARCHAR(100) NOT NULL,
  `created_by` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(100) NOT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `knowledgeBase`.`aticles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgeBase`.`aticles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `subtitle` VARCHAR(250) NOT NULL,
  `status` ENUM('draft', 'publish', 'cancel') NOT NULL,
  `viewers` INT NOT NULL,
  `liked` ENUM('poor', 'average', 'great') NULL,
  `slug` VARCHAR(100) NOT NULL,
  `created_by` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(100) NOT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `content` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `knowledgeBase`.`section_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgeBase`.`section_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `section_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_section_categories_1_idx` (`section_id` ASC) VISIBLE,
  INDEX `fk_section_categories_2_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_section_categories_1`
    FOREIGN KEY (`section_id`)
    REFERENCES `knowledgeBase`.`sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_section_categories_2`
    FOREIGN KEY (`category_id`)
    REFERENCES `knowledgeBase`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `knowledgeBase`.`section_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgeBase`.`section_tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `section_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_section_tags_1_idx` (`section_id` ASC) VISIBLE,
  INDEX `fk_section_tags_2_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `fk_section_tags_1`
    FOREIGN KEY (`section_id`)
    REFERENCES `knowledgeBase`.`sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_section_tags_2`
    FOREIGN KEY (`tag_id`)
    REFERENCES `knowledgeBase`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `knowledgeBase`.`category_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgeBase`.`category_tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_tag` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_tags_1_idx` (`category_tag` ASC) VISIBLE,
  INDEX `fk_category_tags_2_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_tags_1`
    FOREIGN KEY (`category_tag`)
    REFERENCES `knowledgeBase`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_tags_2`
    FOREIGN KEY (`tag_id`)
    REFERENCES `knowledgeBase`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `knowledgeBase`.`article_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgeBase`.`article_tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `article_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_article_tags_1_idx` (`article_id` ASC) VISIBLE,
  INDEX `fk_article_tags_2_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `fk_article_tags_1`
    FOREIGN KEY (`article_id`)
    REFERENCES `knowledgeBase`.`aticles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_tags_2`
    FOREIGN KEY (`tag_id`)
    REFERENCES `knowledgeBase`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
